// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionPlanner.Data;

#nullable disable

namespace ProductionPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024184246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductionPlanner.Models.ProductionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ImprovedJumat")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedKamis")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedMinggu")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedRabu")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedSabtu")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedSelasa")
                        .HasColumnType("int");

                    b.Property<int>("ImprovedSenin")
                        .HasColumnType("int");

                    b.Property<int>("Jumat")
                        .HasColumnType("int");

                    b.Property<int>("Kamis")
                        .HasColumnType("int");

                    b.Property<int>("Minggu")
                        .HasColumnType("int");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Task2");

                    b.Property<int>("Rabu")
                        .HasColumnType("int");

                    b.Property<int>("Sabtu")
                        .HasColumnType("int");

                    b.Property<int>("Selasa")
                        .HasColumnType("int");

                    b.Property<int>("Senin")
                        .HasColumnType("int");

                    b.Property<int>("TotalProduction")
                        .HasColumnType("int");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
