// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionPlannerDB.Data;

#nullable disable

namespace ProductionPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductionPlannerDB.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Jumat")
                        .HasColumnType("int");

                    b.Property<int>("Kamis")
                        .HasColumnType("int");

                    b.Property<int>("Minggu")
                        .HasColumnType("int");

                    b.Property<int>("Rabu")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<int>("Sabtu")
                        .HasColumnType("int");

                    b.Property<int>("Selasa")
                        .HasColumnType("int");

                    b.Property<int>("Senin")
                        .HasColumnType("int");

                    b.Property<int>("TotalAkhir")
                        .HasColumnType("int");

                    b.Property<int>("TotalAwal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plannings");
                });
#pragma warning restore 612, 618
        }
    }
}
